version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: elysia_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: ElysiaDB
      MYSQL_USER: elysia
      MYSQL_PASSWORD: elysia1234
    ports:
      - "13306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  redis:
    image: redis:7.0-alpine
    container_name: elysia_redis
    ports:
      - "6379:6379"

volumes:
  mysql_data:
